# Generated by Django 2.0.6 on 2020-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('insertip', models.CharField(blank=True, max_length=128, verbose_name='内网地址')),
                ('useport', models.CharField(blank=True, max_length=128, verbose_name='使用端口')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='用户名')),
                ('passwd', models.CharField(blank=True, max_length=32, verbose_name='密码')),
                ('DBschame', models.CharField(blank=True, max_length=128, verbose_name='URLDBschame')),
                ('DBschamename', models.CharField(blank=True, max_length=32, verbose_name='URLDBschamename')),
                ('DBschamepasswd', models.CharField(blank=True, max_length=32, verbose_name='URLDBschamepasswd')),
                ('notice', models.TextField(blank=True, max_length=128, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('env', models.CharField(blank=True, max_length=32, verbose_name='环境选项')),
                ('insertip', models.CharField(blank=True, max_length=128, verbose_name='内网地址')),
                ('outip', models.CharField(blank=True, max_length=32, verbose_name='外网地址')),
                ('useport', models.CharField(blank=True, max_length=128, verbose_name='使用端口')),
                ('address', models.TextField(blank=True, max_length=128, verbose_name='主机位置')),
                ('deployapps', models.TextField(blank=True, max_length=128, verbose_name='部署应用')),
                ('usedinfo', models.CharField(blank=True, max_length=32, verbose_name='使用情况')),
                ('ship', models.TextField(blank=True, max_length=128, verbose_name='外内关系')),
                ('urlinfo', models.TextField(blank=True, max_length=128, verbose_name='访问url')),
            ],
        ),
    ]
