# Generated by Django 2.0.6 on 2020-01-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='cpuinfo',
            field=models.CharField(blank=True, max_length=32, verbose_name='cpuinfo'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='diskinfo',
            field=models.CharField(blank=True, max_length=32, verbose_name='diskinfo'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='meminfo',
            field=models.CharField(blank=True, max_length=32, verbose_name='meminfo'),
        ),
    ]
