# Generated by Django 2.0.6 on 2020-01-15 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200110_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='projectname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='是何项目'),
            preserve_default=False,
        ),
    ]
